import { useState } from "react";
import { ChevronDown, ChevronRight, Sparkles, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { fetchExplanation, type ExplainResponse, type FplTeamRecommendation } from "@/lib/fplAssistantApi";

interface ExplanationPanelProps {
  recommendation?: FplTeamRecommendation;
}

export const ExplanationPanel = ({ recommendation }: ExplanationPanelProps) => {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<ExplainResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const toggle = async () => {
    const next = !open;
    setOpen(next);
    if (next && !data && !loading && recommendation) {
      setLoading(true);
      setError(null);
      try {
        const result = await fetchExplanation(recommendation);
        setData(result);
        if (result.error) setError(result.error);
      } catch (err) {
        setError(err instanceof Error ? err.message : String(err));
      } finally {
        setLoading(false);
      }
    }
  };

  const playerName = (id: number | null | undefined): string => {
    if (!id || !recommendation) return "—";
    const all = [...recommendation.starting_xi, ...recommendation.bench];
    const found = all.find((p) => p.player_id === id);
    return found?.web_name ?? `#${id}`;
  };

  if (!recommendation) return null;

  return (
    <div className="mt-4 rounded-lg border border-border bg-card/50">
      <button
        type="button"
        onClick={toggle}
        className="flex w-full items-center justify-between gap-2 px-4 py-3 text-left hover:bg-muted/50 rounded-lg transition-colors"
      >
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="font-medium text-sm">Why these picks?</span>
          <Badge variant="outline" className="text-[10px]">AI</Badge>
        </div>
        {open ? <ChevronDown className="h-4 w-4 text-muted-foreground" /> : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
      </button>

      {open && (
        <div className="border-t border-border px-4 py-3 space-y-3 text-sm">
          {loading && (
            <div className="flex items-center gap-2 text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              Generating rationale…
            </div>
          )}

          {error && !loading && (
            <div className="text-destructive text-xs">
              <p>Could not generate explanation: {error}</p>
              <Button size="sm" variant="outline" className="mt-2" onClick={() => { setData(null); setError(null); toggle(); }}>
                Retry
              </Button>
            </div>
          )}

          {data && !loading && !error && (
            <>
              {data.transfers && data.transfers.length > 0 && (
                <div>
                  <h4 className="font-semibold mb-1.5">Transfer rationale</h4>
                  <ul className="space-y-2">
                    {data.transfers.map((t, i) => (
                      <li key={i} className="text-muted-foreground">
                        <span className="text-foreground font-medium">
                          {playerName(t.out_id)} → {playerName(t.in_id)}:
                        </span>{" "}
                        {t.rationale}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {data.captain && data.captain.rationale && (
                <div>
                  <h4 className="font-semibold mb-1.5">Captain pick</h4>
                  <p className="text-muted-foreground">
                    <span className="text-foreground font-medium">{playerName(data.captain.player_id)}:</span>{" "}
                    {data.captain.rationale}
                  </p>
                </div>
              )}

              {data.chip && data.chip.name && data.chip.rationale && (
                <div>
                  <h4 className="font-semibold mb-1.5">Chip strategy</h4>
                  <p className="text-muted-foreground">
                    <span className="text-foreground font-medium">{data.chip.name}:</span> {data.chip.rationale}
                  </p>
                </div>
              )}

              {data.model && (
                <p className="text-[10px] text-muted-foreground/60 pt-1">
                  Generated by {data.model}{data.cached ? " (cached)" : ""}
                </p>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
};
